name: 'BTC EmbeddedPlatform GitHub Actions Library'
description: 'Runs BTC EmbeddedPlatform Pipeline'
inputs:
  BTCPipePath:
    description: 'Path of the pipeline YML. This YML defines the workflow for BTC according to the specification at [TODO url].'
    required: true
runs:
  using: 'node16'
  main: '${{github.action_repository}}/lib/globalEntrypoint.js'